=== dcgibbons/learning/school/uphoenix/web432/dcg-wk4.dtd
<?xml version="1.0" encoding="utf-8"?>
<!--
  Week 4 Assignment
  David C. Gibbons
  WEB/432 - Web Programming III
  Ganesh Shan
  December 18, 2006
  -->
<!ELEMENT book (authors, sections)>
<!ATTLIST book title CDATA #REQUIRED>

<!ELEMENT authors (author+)>

<!ELEMENT author (#PCDATA)>

<!ELEMENT sections (section+)>

<!ELEMENT section (para+)>
<!ATTLIST section id CDATA #REQUIRED
                  type (acknowledgements | chapter | appendix | references) #REQUIRED
                  title CDATA #REQUIRED>

<!ELEMENT para (#PCDATA)>

=== dcgibbons/learning/school/uphoenix/web432/dcg-wk4.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  Week 4 Assignment
  David C. Gibbons
  WEB/432 - Web Programming III
  Ganesh Shan
  December 18, 2006
  -->
<!DOCTYPE book SYSTEM "dcg-wk4.dtd">
<book title="A Concise History of XML">
    <authors>
      <author>Bob Smith</author>
      <author>Amy Jones</author>
    </authors>

    <sections>
      <section id="acknowledgements" type="acknowledgements" title="Acknowledgements">
        <para>
          Duis blandit nulla amet ea quis volutpat suscipit exerci eros duis dolore feugiat,
          commodo, duis vero, velit suscipit enim sed autem odio. Vulputate zzril blandit eum
          eum facilisi vero feugait iriure, et consequat. Molestie, accumsan velit ipsum
          praesent accumsan dolore delenit in hendrerit, at enim dolor. 
        </para>
      </section>
      <section id="chap01" type="chapter" title="The First Chapter">
        <para>
          Duis blandit nulla amet ea quis volutpat suscipit exerci eros duis dolore feugiat,
          commodo, duis vero, velit suscipit enim sed autem odio. Vulputate zzril blandit eum
          eum facilisi vero feugait iriure, et consequat. Molestie, accumsan velit ipsum
          praesent accumsan dolore delenit in hendrerit, at enim dolor. Ea dignissim ut commodo
          odio consequat consectetuer augue dignissim ea ut velit sed accumsan veniam. Ut
          nostrud vulputate, magna nulla exerci eu in illum luptatum autem commodo nibh nibh.
          Augue tation hendrerit suscipit, consequat nulla wisi, suscipit ea velit nulla
          molestie. In autem, ut consequat, exerci blandit, esse, aliquip dolore, eros veniam
          aliquip duis, vel.
        </para>
        <para>
          Dolore diam te elit nostrud, vulputate wisi augue facilisis et et et euismod minim
          adipiscing, esse dolor autem tation consequat. Facilisis lorem ut quis zzril, te
          feugiat duis iriure eu commodo, et, consequat vel. Exerci molestie luptatum lobortis
          iusto consequat minim tation blandit, nostrud eu qui esse laoreet.
        </para>
        <para>
          Vulputate zzril blandit eum eum facilisi vero feugait iriure, et consequat. Molestie,
          accumsan velit ipsum praesent accumsan dolore delenit in hendrerit, at enim dolor. Ea
          dignissim ut commodo odio consequat consectetuer augue dignissim ea ut velit sed accumsan
          veniam. Ut nulla duis sed praesent volutpat in ea in et lobortis tation dolor, dolor.         
        </para>
      </section>
      <section id="chap02" type="chapter" title="The Second Chapter">
        <para>
          Dolore diam te elit nostrud, vulputate wisi augue facilisis et et et euismod minim
          adipiscing, esse dolor autem tation consequat. Facilisis lorem ut quis zzril, te
          feugiat duis iriure eu commodo, et, consequat vel. Exerci molestie luptatum lobortis
          iusto consequat minim tation blandit, nostrud eu qui esse laoreet.
        </para>
        <para>
          Vulputate zzril blandit eum eum facilisi vero feugait iriure, et consequat. Molestie,
          accumsan velit ipsum praesent accumsan dolore delenit in hendrerit, at enim dolor. Ea
          dignissim ut commodo odio consequat consectetuer augue dignissim ea ut velit sed accumsan
          veniam. Ut nulla duis sed praesent volutpat in ea in et lobortis tation dolor, dolor.
        </para>
      </section>
      <section id="chap03" type="chapter" title="The Third Chapter">
        <para>
          Vulputate zzril blandit eum eum facilisi vero feugait iriure, et consequat. Molestie,
          accumsan velit ipsum praesent accumsan dolore delenit in hendrerit, at enim dolor. Ea
          dignissim ut commodo odio consequat consectetuer augue dignissim ea ut velit sed accumsan
          veniam. Ut nulla duis sed praesent volutpat in ea in et lobortis tation dolor, dolor.
        </para>
      </section>
    </sections>
</book>
