=== dcgibbons/learning/school/uphoenix/web432/team/supplychain.dtd
<?xml version="1.0" encoding="utf-8"?>
<!--
  Riordan Manufacturing Supply Chain 
  XML Document Type Definition
  Janet Carlin, David C. Gibbons
  WEB/432 - Web Programming III
  Ganesh Shan
  January 8, 2007
  -->
<!ELEMENT supplychain (order*, fulfillment*, transport*)>
<!ATTLIST supplychain timestamp CDATA #REQUIRED>

<!ELEMENT order (requester, vendor, product, quantity)>
<!ATTLIST order orderId CDATA #REQUIRED>

<!ELEMENT requester (#PCDATA)>

<!ELEMENT vendor (#PCDATA)>

<!ELEMENT product (#PCDATA)>
<!ATTLIST product productCode CDATA #REQUIRED>

<!ELEMENT quantity (#PCDATA)>

<!ELEMENT fulfillment (customer, vendor, product, quantity)>
<!ATTLIST fulfillment orderId CDATA #REQUIRED
                      customerOrderId CDATA #REQUIRED>

<!ELEMENT customer (#PCDATA)>

<!ELEMENT transport (vendor, source, destination, shipments+)>

<!ELEMENT source (#PCDATA)>
<!ATTLIST source id CDATA #REQUIRED>

<!ELEMENT destination (#PCDATA)>
<!ATTLIST destination id CDATA #REQUIRED>

<!ELEMENT shipments (shipment+)>

<!ELEMENT shipment EMPTY>
<!ATTLIST shipment id CDATA #REQUIRED
                   customerId CDATA #REQUIRED>

=== dcgibbons/learning/school/uphoenix/web432/team/transport1.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  Riordan Manufacturing Supply Chain
  XML Sample Data - Transportation
  Learning Team A Final Project
  Janet Carlin, David C. Gibbons
  WEB/432 - Web Programming III
  Ganesh Shan
  January 8, 2007
  -->
<!DOCTYPE supplychain SYSTEM "supplychain.dtd">
<supplychain timestamp="01/07/2007 18:54">
  <transport>
    <vendor>Huffman Trucking</vendor>
    <source id="brooks001">Brooks Chemical Supply</source>
    <destination id="riordan001">Riordan Manufacturing</destination>
    <shipments>
      <shipment id="000993121" customerId="993921"/>
      <shipment id="000993122" customerId="993922"/>
    </shipments>
  </transport>
</supplychain>
